name: Documentation

on:
  push:
    branches: 
      - sprint3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build
      uses: codevise/documentation-js-action@v1
      with:
        input: ./source
        output: ./docs

      # - name: Build
      #   uses: andstor/jsdoc-action@v1
      #   with:
      #     source_dir: ./source
      #     output_dir: ./docs
      #     config_file: conf.json
      #     template: minami
      #     front_page: docs.md