name: Documentation

on:
  push:
    branches: 
      - sprint3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      # - name: Build
      #   uses: andstor/jsdoc-action@v1
      #   with:
      #     source_dir: ./source
      #     output_dir: ./docs
      #     config_file: conf.json
      #     template: minami
      #     front_page: docs.md

      - name: Build
        uses: nidhigiridhar/cse110-w21-group35@v0.32
        with:
          source_dir: ./source
          recurse: true
          output_dir: ./docs
          config_file: conf.json
          template: minami
          front_page: docs.md

      - name: Deploy
        run: |
          npm install --save-dev jsdoc
          ./node_modules/.bin/jsdoc ./source/timer.js