name: Documentation

on:
  push:
    branches: 
      - sprint3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          output_dir: ./docs
          config_file: conf.json
          template: minami
      
      - name: Deploy
        run: |
          npm install --save-dev jsdoc
          ./node_modules/.bin/jsdoc ./source/timer.js ./docs
          ./node_modules/.bin/jsdoc ./source/notifications.js ./docs
          ./node_modules/.bin/jsdoc ./source/color-change.js ./docs
          ./node_modules/.bin/jsdoc ./source/breakReminder.js ./docs