name: Unit Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          cd pipeline
          npm install
          npm jest subtraction.test.js