name: Unit Tests

on:
  pull_request:
    branches:
      - master
      - timer
  push:
    branches:
      - master
      - notifications

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install
          npm test notifications.test.js
