name: Unit Tests

on:
  pull_request:
    branches:
      - timer
  push:
    branches:
      - notifications

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install
          npm test ./source/notifications.test.js
          npm test ./source/notifications.showNotif.test.js
