name: Unit Tests

on:
  push:
    branches: [pipeline]
  pull_request:
    branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /cse110-w21-group/pipeline
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests